AWSTemplateFormatVersion: 2010-09-09
Description: CI/CD Pipeline for AWS Resource Deployment

Parameters:
  GitHubOwner:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]*"
    Default: fatuboy
  GitHubRepositoryName:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]*"
    Default: aws-cloudformation-templates
  GitHubBranch:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]*"
    Default: master
  GitHubToken:
    Type: String
    # AllowedPattern: "[A-Za-z0-9-]*"
    Default: '{{resolve:secretsmanager:GITHUB_ACCESS:SecretString:GITHUB_ACCESS_TOKEN}}'

Resources:  
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref AWS::StackName
      Description: CodeBuild Pipleline Project
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED, PULL_REQUEST_REOPENED
            - Type: BASE_REF
              Pattern: !Sub  refs/heads/${GitHubBranch}$
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
      Source:
        Location: !Sub https://github.com/${GitHubOwner}/${GitHubRepositoryName}.git
        Type: GITHUB
        BuildSpec: buildspec.yaml
        Auth: 
          Type: OAUTH
          Resource: !Ref CodeBuildSourceCredential
      TimeoutInMinutes: 10

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns: 
        - !Ref CodeBuildServiceRolePolicy
  
  CodeBuildServiceRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
        ManagedPolicyName: CodeBuildServiceRolePolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Sid: CloudWatchLogsPolicy
              Effect: Allow
              Action:
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
              Resource: '*'
            - Sid: CodeCommitPolicy
              Effect: Allow
              Action:
                - 'codecommit:GitPull'
              Resource: '*'
            - Sid: S3GetObjectPolicy
              Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:GetObjectVersion'
              Resource: '*'
            - Sid: S3PutObjectPolicy
              Effect: Allow
              Action:
                - 's3:PutObject'
              Resource: '*'
            - Sid: S3BucketIdentity
              Effect: Allow
              Action:
                - 's3:GetBucketAcl'
                - 's3:GetBucketLocation'
              Resource: '*'

  CodeBuildSourceCredential:  
    Type: AWS::CodeBuild::SourceCredential
    Properties: 
      AuthType: PERSONAL_ACCESS_TOKEN
      ServerType: GITHUB
      Token: !Ref GitHubToken

  CodePipeline: 
    Type: AWS::CodePipeline::Pipeline 
    Properties: 
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      Stages: 
        - Name: Source 
          Actions: 
            - Name: Source
              ActionTypeId: 
                Category: Source 
                Owner: ThirdParty 
                Version: 1 
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepositoryName
                Branch: !Ref GitHubBranch
                PollForSourceChanges: 'false'
                OAuthToken: !Ref GitHubToken
              OutputArtifacts: 
                - Name: SourceCode
        - Name: Build 
          Actions: 
            - Name: Build 
              ActionTypeId: 
                Category: Build 
                Owner: AWS 
                Version: 1 
                Provider: CodeBuild
              Configuration: 
                ProjectName: !Ref CodeBuildProject
              OutputArtifacts:
                - Name: BuildOutput
              InputArtifacts:
                - Name: SourceCode
              RunOrder: 1 
      ArtifactStore: 
        Type: S3 
        Location:
          Ref: CodePipelineArtifactStore 

  
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns: 
        - !Ref CodePipelneServiceRolePolicy
  
  CodePipelneServiceRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
        ManagedPolicyName: CodePipelineServiceRolePolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Sid: CloudWatchLogsPolicy
              Effect: Allow
              Action:
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
              Resource: '*'
            - Sid: CodeCommitPolicy
              Effect: Allow
              Action:
                - 'codecommit:GitPull'
              Resource: '*'
            - Sid: S3GetObjectPolicy
              Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:GetObjectVersion'
              Resource: '*'
            - Sid: S3PutObjectPolicy
              Effect: Allow
              Action:
                - 's3:PutObject'
              Resource: '*'
            - Sid: S3BucketIdentity
              Effect: Allow
              Action:
                - 's3:GetBucketAcl'
                - 's3:GetBucketLocation'
              Resource: '*'
            - Sid: CodebuildPolicy  
              Effect: Allow
              Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              Resource: "*"

  CodePipelineArtifactStore:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration: 
        Status: Enabled

  CodePipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties: 
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration: 
        SecretToken: !Ref GitHubToken
      RegisterWithThirdParty: 'true'
      Filters: 
        - JsonPath: '$.ref'
          MatchEquals: 'refs/heads/{Branch}'
        - JsonPath: '$.repository.name'
          MatchEquals: '{Repo}'
      TargetPipeline: !Ref CodePipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt CodePipeline.Version