AWSTemplateFormatVersion: 2010-09-09
Description: CI/CD Pipeline for AWS Resource Deployment

Parameters:
  GitHubOwner:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]*"
    Default: fatuboy
  GitHubReporsitoryName:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]*"
    Default: aws-cloudformation-templates
  GitHubBranch:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]*"
    Default: master

Resources:  
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref AWS::StackName
      Description: CodeBuild Pipleline Project
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED, PULL_REQUEST_REOPENED
            - Type: BASE_REF
              Pattern: !Sub  refs/heads/${GitHubBranch}$
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
      Source:
        Location: !Sub https://github.com/${GitHubOwner}/${GitHubReporsitoryName}.git
        Type: GITHUB
        BuildSpec: buildspec.yaml
        Auth: 
          Type: OAUTH
          Resource: !Ref CodeBuildSourceCredential
      TimeoutInMinutes: 10

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns: 
        - !Ref CodeBuildServiceRolePolicy
  
  CodeBuildServiceRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
        ManagedPolicyName: CodeBuildServiceRolePolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Sid: CloudWatchLogsPolicy
              Effect: Allow
              Action:
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
              Resource: '*'
            - Sid: CodeCommitPolicy
              Effect: Allow
              Action:
                - 'codecommit:GitPull'
              Resource: '*'
            - Sid: S3GetObjectPolicy
              Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:GetObjectVersion'
              Resource: '*'
            - Sid: S3PutObjectPolicy
              Effect: Allow
              Action:
                - 's3:PutObject'
              Resource: '*'
            - Sid: S3BucketIdentity
              Effect: Allow
              Action:
                - 's3:GetBucketAcl'
                - 's3:GetBucketLocation'
              Resource: '*'

  CodeBuildSourceCredential:  
    Type: AWS::CodeBuild::SourceCredential
    Properties: 
      AuthType: PERSONAL_ACCESS_TOKEN
      ServerType: GITHUB
      Token: '{{resolve:secretsmanager:GITHUB_ACCESS:SecretString:GITHUB_ACCESS_TOKEN}}'